### ISSUE TITLE
移动端主页模糊

### ISSUE THREAD

**Issue by Cxyofficial** [Alittfre/vitepress-theme-bluearchive#15]
在移动端浏览器打开主页 那个模糊遮罩会跟着个人签名的打字动画一起动 能不能把遮罩固定住？

**Comment by naahi-i** [comment]
是换行时候的抖动么

**Comment by Cxyofficial** [comment]
不是 是虚化框会随着打字动画展开来

**Comment by naahi-i** [comment]
via浏览器没遇到过

**Comment by Cxyofficial** [comment]
我也是via😭

**Comment by Cxyofficial** [comment]
从这样展开变成这样
![Screenshot_2024-08-25-18-13-21-158_mark.via.jpg](https://github.com/user-attachments/assets/8ecb3faf-1163-4151-8f4d-66d8be056b3b)

![Screenshot_2024-08-25-18-13-12-787_mark.via.jpg](https://github.com/user-attachments/assets/beb095ce-84ee-4c03-909f-16c8a810eada)

**Comment by naahi-i** [comment]
你是不是碰到什么代码了，我刚刚去你网站看了有这个问题

**Comment by Cxyofficial** [comment]
不知道 能看看你的网站吗

**Comment by naahi-i** [comment]
> 不知道 能看看你的网站吗

https://ngnhomepage.top
也可以直接来我仓库找

**Comment by Cxyofficial** [comment]
啊？ 这我不知道了 我前天把整个库重新拉了一遍的 只改了config还有添加了md文件

**Comment by naahi-i** [comment]
> 啊？ 这我不知道了 我前天把整个库重新拉了一遍的 只改了config还有添加了md文件

我也合并了更新，不过我不是复刻的仓库， 是比对提交手动合并的

**Comment by Cxyofficial** [comment]
奇怪了

**Comment by Cxyofficial** [comment]
> > 啊？ 这我不知道了 我前天把整个库重新拉了一遍的 只改了config还有添加了md文件
> 
> 我也合并了更新，不过我不是复刻的仓库， 是比对提交手动合并的

等等 我看了下模板网站也是一样的情况

**Comment by naahi-i** [comment]
> > 
> > 我也合并了更新，不过我不是复刻的仓库， 是比对提交手动合并的
> 
> 等等 我看了下模板网站也是一样的情况

我看模板也是正常的啊

**Comment by Cxyofficial** [comment]
> 
> > > 
> > > 我也合并了更新，不过我不是复刻的仓库， 是比对提交手动合并的
> > 
> > 等等 我看了下模板网站也是一样的情况
> 
> 我看模板也是正常的啊![Screenshot_2024-08-25-18-36-37-97_a252b927494330cdc2c8ba3b3f952e5e.jpg](https://github.com/user-attachments/assets/935ad879-c0a0-4518-8bbf-76a001ed0398)
> 
> 

懵逼了

**Comment by Cxyofficial** [comment]
@Alittfre 麻烦帮我看看我仓库的代码哪里出问题了 谢谢！

**Comment by naahi-i** [comment]
我比较了一下config和banner.vue之类的文件除了自定义的地方外没看到哪里不一样

**Comment by Alittfre** [comment]
改了

**Comment by Cxyofficial** [comment]
> 改了

已解决 感谢作者

**Comment by Cxyofficial** [comment]
> 改了

emmmm 移动端的高度也要固定下
