### ISSUE TITLE
尝试添加新的navbar无反应

### ISSUE THREAD

**Issue by XokoukioX** [Alittfre/vitepress-theme-bluearchive#16]
如下,在`config.mts`中填写

      themeConfig: {
        // navBar
        menuList: [
          { name: '首页', url: '' },
          { name: '标签', url: 'tags/' },
          { name: '小说', url: 'novel/' },
          { name: 'test', url: 'posts/' }
        ],

**编译之后为**
![image](https://github.com/user-attachments/assets/6d1dcda0-7fb8-4f01-a8d8-85725e88c716)

**同时文件树也创建了相关文件夹和文件**
![image](https://github.com/user-attachments/assets/aa5cbcc2-6e67-43d7-a8a2-f5c7bc297e01)
**但是实际显示效果如下**
![image](https://github.com/user-attachments/assets/86daaf44-ca28-4440-8b06-6fd17b2d00ec)

**Comment by Alittfre** [comment]
加新的navbar要改的地方挺多的哦，页面你也要自己写和设计

**Comment by XokoukioX** [comment]
好的
