### ISSUE TITLE
从[标签]切换回[首页]时welcomebox的模糊会延迟出现

### ISSUE THREAD

**Issue by naahi-i** [Alittfre/vitepress-theme-bluearchive#17]
![image](https://github.com/user-attachments/assets/f719ec31-0bc3-417a-9bdb-acba8edaad20)
也包括从帖子回主页时

**Comment by Alittfre** [comment]
渐隐效果和模糊不能叠加，只能这样了，也不是很明显吧

**Comment by naahi-i** [comment]
其实突然闪一下还挺明显的，如果不能同时可以延迟渐变模糊也行

**Comment by naahi-i** [comment]
在我的仓库里尝试解决了https://github.com/naahi-i/ngn-myhomepage/commit/1d3ecac3a59fbfa075bf514f52716ba3e2477ec0
用的onMounted延迟，不过会导致整个box的出现时间变长

**Comment by Alittfre** [comment]
也行吧，可以提个pr我合一下😋

**Comment by naahi-i** [comment]
> 也行吧，可以提个pr我合一下😋

我不是复刻的仓库提不了![Image_1724809793321.png](https://github.com/user-attachments/assets/7fc01102-4eec-47d6-a54e-1019b5a210cb)

**Comment by Alittfre** [comment]
那我后续加上你的一些动效吧，会注明引用，可以吗

**Comment by naahi-i** [comment]
> 那我后续加上你的一些动效吧，会注明引用，可以吗

当然可以![Image_1724810527141.jpg](https://github.com/user-attachments/assets/a71ebd1b-25d0-4141-a032-2366e8d7aeb1)
