### ISSUE TITLE
icon图标可以加一个酷安吗

### ISSUE THREAD

**Issue by Cxyofficial** [Alittfre/vitepress-theme-bluearchive#20]

**Comment by Alittfre** [comment]
.vitepress\theme\assets\icon里有图标，使用阿里巴巴iconfont生成的，你可以去上面加任何想要的图标

**Comment by Cxyofficial** [comment]
> .vitepress\theme\assets\icon里有图标，使用阿里巴巴iconfont生成的，你可以去上面加任何想要的图标

好的👌

**Comment by Cxyofficial** [comment]
> > .vitepress\theme\assets\icon里有图标，使用阿里巴巴iconfont生成的，你可以去上面加任何想要的图标
> 
> 好的👌

怎么加进去？

**Comment by naahi-i** [comment]
> > > .vitepress\theme\assets\icon里有图标，使用阿里巴巴iconfont生成的，你可以去上面加任何想要的图标
> > 
> > 好的👌
> 
> 怎么加进去？
> 


搜在线字体编辑器，把你找到的图标加进去，记得编号，然后去iconfont.css文件里面添加相应的类名
我加音乐控件图标就是这么干的
