### ISSUE TITLE
阿罗娜与首屏加载

### ISSUE THREAD

**Issue by naahi-i** [Alittfre/vitepress-theme-bluearchive#25]
首屏加载动画以判断网页是否全部加载完成为条件隐藏

**Comment by Alittfre** [comment]
由于是静态网站并且使用了JS框架，好像没有什么方法能判断网页资源加载完成哦

**Comment by naahi-i** [comment]
> 由于是静态网站并且使用了JS框架，好像没有什么方法能判断网页资源加载完成哦

唔

**Comment by naahi-i** [comment]
在尝试解决二级菜单的层级问题，这种横向式的会不会更好点？
![image](https://github.com/user-attachments/assets/1df1746b-a10d-4772-a941-a96b8573c521)

**Comment by Alittfre** [comment]
随你喜好，我个人还是喜欢竖向的

**Comment by Cxyofficial** [comment]
![Screenshot_2024-09-14-23-03-11-915_mark.via.jpg](https://github.com/user-attachments/assets/845d6896-bd02-41ff-903a-0fe3f05b2d99)

把音乐图标移除到二级菜单后 顶栏文字似乎有些.....不对称？

**Comment by naahi-i** [comment]
> ![Screenshot_2024-09-14-23-03-11-915_mark.via.jpg](https://github.com/user-attachments/assets/845d6896-bd02-41ff-903a-0fe3f05b2d99)
> 
> 把音乐图标移除到二级菜单后 顶栏文字似乎有些.....不对称？

这个明天看看，我记得当初用的是手动定位来着💦

**Comment by Cxyofficial** [comment]
> > ![Screenshot_2024-09-14-23-03-11-915_mark.via.jpg](https://github.com/user-attachments/assets/845d6896-bd02-41ff-903a-0fe3f05b2d99)
> > 
> > 把音乐图标移除到二级菜单后 顶栏文字似乎有些.....不对称？
> 
> 这个明天看看，我记得当初用的是手动定位来着💦

额 这个似乎还没解决

**Comment by Alittfre** [comment]
> > > ![Screenshot_2024-09-14-23-03-11-915_mark.via.jpg](https://private-user-images.githubusercontent.com/127767886/367523696-845d6896-bd02-41ff-903a-0fe3f05b2d99.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODQ0MDEsIm5iZiI6MTcyOTU4NDEwMSwicGF0aCI6Ii8xMjc3Njc4ODYvMzY3NTIzNjk2LTg0NWQ2ODk2LWJkMDItNDFmZi05MDNhLTBmZTNmMDViMmQ5OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMlQwODAxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZWMyMDlmZDI2MTg4ZjUyOWQ4NzY3MDQwNjdiMzgyM2E1NDIwZThiOWM1NzYxZmY4Njg0NjI5N2Q0N2U5ZjgyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lKpGhWcwXgftnRIWhcqVirGY2UeBHULbuR4Z5tWYKKo)
> > > 把音乐图标移除到二级菜单后 顶栏文字似乎有些.....不对称？
> > 
> > 
> > 这个明天看看，我记得当初用的是手动定位来着💦
> 
> 额 这个似乎还没解决

现在应该好了
