### ISSUE TITLE
视频播放器圆角

### ISSUE THREAD

**Issue by Cxyofficial** [Alittfre/vitepress-theme-bluearchive#27]
可以给哔哩哔哩视频网页播放器加上圆角吗

**Comment by naahi-i** [comment]
看[这个提交](https://github.com/naahi-i/ngn-myhomepage/commit/f9696b8c1f74bb71a86403434ce2dfc45eb0a858)

**Comment by Cxyofficial** [comment]
> 看[这个提交](https://github.com/naahi-i/ngn-myhomepage/commit/f9696b8c1f74bb71a86403434ce2dfc45eb0a858)

大佬 牛逼

**Comment by Cxyofficial** [comment]
> > 看[这个提交](https://github.com/naahi-i/ngn-myhomepage/commit/f9696b8c1f74bb71a86403434ce2dfc45eb0a858)
> 
> 大佬 牛逼

这个对
<iframe src="//player.bilibili.com/player.html?isOutside=true&aid=359952556&bvid=BV1tX4y1W73N&cid=1239492166&p=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>
有作用嘛
直接写在md里边的

**Comment by naahi-i** [comment]
> > > 看[这个提交](https://github.com/naahi-i/ngn-myhomepage/commit/f9696b8c1f74bb71a86403434ce2dfc45eb0a858)
> > 
> > 大佬 牛逼
> 
> 这个对
> <iframe src="//player.bilibili.com/player.html?isOutside=true&aid=359952556&bvid=BV1tX4y1W73N&cid=1239492166&p=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>
> 有作用嘛
> 直接写在md里边的
> 
> 

我用你那个视频帖子测试过有效

**Comment by Cxyofficial** [comment]
> > > > 看[这个提交](https://github.com/naahi-i/ngn-myhomepage/commit/f9696b8c1f74bb71a86403434ce2dfc45eb0a858)
> > > 
> > > 大佬 牛逼
> > 
> > 这个对
> > <iframe src="//player.bilibili.com/player.html?isOutside=true&aid=359952556&bvid=BV1tX4y1W73N&cid=1239492166&p=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true"></iframe>
> > 有作用嘛
> > 直接写在md里边的
> > 
> > 
> 
> 我用你那个视频帖子测试过有效

好的 感谢🙏
