### ISSUE TITLE
页面顺滑滚动

### ISSUE THREAD

**Issue by naahi-i** [Alittfre/vitepress-theme-bluearchive#33]
现在滚动起来总感觉顿顿的

**Comment by Alittfre** [comment]
我这还好，但是阿罗娜的性能消耗是挺高的，你关了试试？

**Comment by naahi-i** [comment]
> 我这还好，但是阿罗娜的性能消耗是挺高的，你关了试试？

不是卡顿 应该形容为滚起来咯噔咯噔的？

**Comment by Alittfre** [comment]
我感觉不出来🤨，用的chrome吗？

**Comment by naahi-i** [comment]
> 我感觉不出来🤨，用的chrome吗？

edge 和你在pr里给的那个样例博客对比一下会有点感觉

**Comment by Alittfre** [comment]
edge对滚动有修改
https://blog.csdn.net/weixin_44634372/article/details/114881915

**Comment by naahi-i** [comment]
🤔
